### ISSUE TITLE
논리 모델링

### ISSUE THREAD

**Issue by mini-xi** [beyond-sw-camp/be04-1st-4goda-vite#33]
### 1. 목적

> 바커 표기법을 활용한 논리 모델링

### 2. 기능 설명

- 논리 모델링, 바커 표기법을 사용, 서브타입 생성
- 01/08 서브타입 추가 및 엔티티 갯수 증가

**Comment by mini-xi** [comment]
![바커수정](https://github.com/beyond-sw-camp/be04-1st-4goda-vite/assets/80388847/87a503c6-14dc-4500-9db4-7383d6b3c2bb)

**Comment by goeunpark123** [comment]
엔티티 개수 맞춰서 수정 완료
