### ISSUE TITLE
회원가입

### ISSUE THREAD

**Issue by onelee521** [beyond-sw-camp/be04-1st-4goda-vite#35]
### 1. 목적

> 회원가입
> 

### 2. 기능 설명

- 회원의 정보를 입력하여 저장한다.

**Comment by Sosohy** [comment]
회원의 어떤 정보를 넣을 것인지 명시하면 더 좋을 것 같아요!

**Comment by ms1011** [comment]
회원가입 기능은 필수라 필요한 것 같습니다 😀
