### ISSUE TITLE
회원 탈퇴

### ISSUE THREAD

**Issue by onelee521** [beyond-sw-camp/be04-1st-4goda-vite#38]
### 1. 목적

> 회원 탈퇴

### 2. 기능 설명

- 회원 상태를 탈퇴 상태로 변경한다.

### 3. 참고 사항

- 탈퇴 시 회원 정보가 바로 삭제되지 않는다.

**Comment by Sosohy** [comment]
탈퇴 상태로 변경 시에 정보를 직접적으로 삭제하지 않고 탈퇴날짜를 업데이트 하는 방식이 맞나요?

**Comment by mini-xi** [comment]
확인했습니다

**Comment by Wrinkk** [comment]
체크완료!!

**Comment by onelee521** [comment]
> 탈퇴 상태로 변경 시에 정보를 직접적으로 삭제하지 않고 탈퇴 날짜를 업데이트 하는 방식이 맞나요?

넵 맞습니다.
