### ISSUE TITLE
회원등급반영 기능

### ISSUE THREAD

**Issue by Sosohy** [beyond-sw-camp/be04-1st-4goda-vite#39]
### 1. 목적

> 회원 누적결제금액에 따라 등급 기준에 충족된 회원인 경우,  결제 시 등급별 할인율을 적용하기 위해 회원의 등급 변경
> 

### 2. 기능 설명

- 회원의 누적결제금액에 따른 회원 등급 변경

### 3. 참고 사항

- 누적결제금액 3만원 이상, VIP로 등급 변경
- 누적결제금액 10만원 이상, VVIP로 등급 변경

**Comment by goeunpark123** [comment]
정확한 할인율을 명시한 부분 좋아요!!

**Comment by Wrinkk** [comment]
할인율 명시도 더하면 좋을거 같아요!! 👍

**Comment by onelee521** [comment]
좋은 기능입니다.

**Comment by ms1011** [comment]
회원들이 더욱 열심히 활동할 것으로 보입니다 좋아요😸
