### ISSUE TITLE
초대내역확인 기능

### ISSUE THREAD

**Issue by Sosohy** [beyond-sw-camp/be04-1st-4goda-vite#40]
### 1. 목적

> 회원이 초대 받은 이벤트와 초대한 이벤트를 확인하기 위해 목록 조회

### 2. 기능 설명

- 회원이 초대한 이벤트 목록 조회
- 회원이 초대받은 이벤트 목록 조회

### 3. 참고 사항

- 회원이 초대받은 경우 is_invited = 1
- 회원이 초대한 경우(호스트) is_invited = 0

**Comment by goeunpark123** [comment]
초대여부가 헷갈렸는데 정리되어서 좋아요!

**Comment by Wrinkk** [comment]
좋습니다 👍

**Comment by onelee521** [comment]
초대 받은 이벤트와 초대한 이벤트를 따로 볼 수 있어서 좋습니다.
