### ISSUE TITLE
회원 검색 기능 추가

### ISSUE THREAD

**Issue by ms1011** [beyond-sw-camp/be04-1st-4goda-vite#42]
### 1. 목적

> 특정 회원을 검색하기 위한 기능

### 2. 기능 설명

- 회원 ID로 특정 회원 검색

### 3. 참고 사항
- 회원, 운영자 모두 검색이 가능하다

**Comment by Sosohy** [comment]
네 좋아요~

**Comment by mini-xi** [comment]
회원 검색에 INDEX 기능 사용 되나요?

**Comment by onelee521** [comment]
확인완료

**Comment by ms1011** [comment]
> 확인완료

이슈 close 요청드립니다
