### ISSUE TITLE
닉네임 검색 기능 추가

### ISSUE THREAD

**Issue by ms1011** [beyond-sw-camp/be04-1st-4goda-vite#43]
### 1. 목적

> 회원ID뿐 아니라 닉네임으로도 검색이 가능하게 하기 위해

### 2. 기능 설명

- 닉네임으로 특정 회원 검색

### 3. 참고 사항
- #42 회원ID와 비슷한 기능을 제공한다

**Comment by mini-xi** [comment]
닉네임으로 기능 확인 좋습니다

**Comment by Wrinkk** [comment]
좋아요~ 👍

**Comment by onelee521** [comment]
확인했습니다.

**Comment by ms1011** [comment]
> 확인했습니다.

@onelee521 이슈 close 요청 드립니다
