### ISSUE TITLE
이벤트 초대 기능 추가

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-1st-4goda-vite#44]
### 1. 목적

> 이벤트에 게스트를 초대
> 

### 2. 기능 설명

- 이벤트 테이블에 이벤트 정보 INSERT
- 게스트명단 테이블에 이벤트에 초대된 모든 게스트 정보 INSERT

### 3. 참고 사항

트랜젝션으로 두 개의 쿼리가 한 번에 실행

**Comment by Sosohy** [comment]
실행 순서는 기능에 있는 순서대로 맞을까요?

**Comment by goeunpark123** [comment]
> 실행 순서는 기능에 있는 순서대로 맞을까요?

네 이벤트 PK가 게스트명단의 FK로 사용되기 때문에 이 순서가 맞습니다!

**Comment by onelee521** [comment]
트랜젝션 사용 좋습니다.

**Comment by ms1011** [comment]
트랜잭션으로 사용하여 깔끔한 기능처리가 가능할 것 같네요  훌륭합니다🐵🐵
