### ISSUE TITLE
이벤트 삭제 기능 추가

### ISSUE THREAD

**Issue by Wrinkk** [beyond-sw-camp/be04-1st-4goda-vite#45]
### 1. 목적

- 기존의 약속이 취소 되는경우 이벤트를 취소하기 위함.

### 2. 기능 설명

- 선택한 이벤트 삭제 기능

**Comment by Sosohy** [comment]
넵 확인인했습니다

**Comment by onelee521** [comment]
이벤트 삭제 기능 추가 좋습니다

**Comment by ms1011** [comment]
이벤트 취소 됐을 경우에 잘 쓰일 것 같습니다 좋아요 👍👍
