### ISSUE TITLE
이벤트 공개 기능 추가

### ISSUE THREAD

**Issue by mini-xi** [beyond-sw-camp/be04-1st-4goda-vite#46]
### 1. 목적

> 이벤트를 공개함으로써 인기 이벤트 구분 및 회원이 '좋아요'로 표시한 이벤트 찾기 위함

### 2. 기능 설명

- 이벤트 공개 및 비공개 중 공개로 표시한다

**Comment by Wrinkk** [comment]
좋은 기능인거 같습니다 👍

**Comment by Sosohy** [comment]
공개하고 싶지 않은 회원도 있을 경우를 대비해서 공개/비공개 나누는게 좋은 것 같아요!

**Comment by onelee521** [comment]
다양한 이벤트들이 공개할 수 있는게 좋습니다.
