### ISSUE TITLE
이벤트 비공개 기능 추가

### ISSUE THREAD

**Issue by mini-xi** [beyond-sw-camp/be04-1st-4goda-vite#47]
### 1. 목적

> 이벤트를 비공개함으로써 호스트가 이벤트를 다른 사람에게 보이지 않도록 설정

### 2. 기능 설명

- 이벤트 공개와 비공개 중 비공개로 전환

**Comment by goeunpark123** [comment]
비공개와 공개 속성과 값을 명시해주시면 좋을 것 같아요~

**Comment by Wrinkk** [comment]
ture false 가 공개 비공개인지 적으면 될거같아요!! 👍

**Comment by onelee521** [comment]
공개 비공개 추가 설명 부탁드려요!
