### ISSUE TITLE
이벤트 RSVP

### ISSUE THREAD

**Issue by onelee521** [beyond-sw-camp/be04-1st-4goda-vite#48]
### 1. 목적

> 이벤트에 대한 참석여부 답장

### 2. 기능 설명

- 초대 받은 이벤트에 대해 참석여부에 대한 답장을 보낸다.

### 3. 참고 사항

- 참석 시 참석여부 상태가 True로 변경

**Comment by Sosohy** [comment]
답장 기능 좋아요!

**Comment by Wrinkk** [comment]
참석 여부 는 중요하다 생각이들어요 👍
