### ISSUE TITLE
이벤트 발송

### ISSUE THREAD

**Issue by onelee521** [beyond-sw-camp/be04-1st-4goda-vite#49]
### 1. 목적

> 이벤트 발송하기
> 

### 2. 기능 설명

- 초대한 이벤트에 대한 발송이 성공하는 것을 확인한다.

### 3. 참고 사항

- 발송 성공 시 성공여부 True로 변경
- 발송 실패 시 재발송

**Comment by goeunpark123** [comment]
재발송 시에 성공여부만 업데이트
새로운 레코드 생성 X

**Comment by mini-xi** [comment]
이벤트 발송이 주요 기능이니까 신경써서 해봅시다

**Comment by Wrinkk** [comment]
좋습니다 ~~ 💯
