### ISSUE TITLE
이벤트좋아요관리 기능

### ISSUE THREAD

**Issue by Sosohy** [beyond-sw-camp/be04-1st-4goda-vite#50]
### 1. 목적

> 회원이 좋아요 표시한 이벤트를 확인하고, 좋아요 수를 통해 이벤트 순위를 계산하기 위해 이벤트에 대한 좋아요 관리
> 

### 2. 기능 설명

- 이벤트ID와 좋아요를 누른 회원의 ID 이벤트좋아요관리 테이블에 INSERT
- 회원이 좋아요한 이벤트 테이블의 좋아요수 증가
- 이벤트ID와 좋아요를 취소한 회원의 ID 이벤트좋아요관리 테이블에서 DELETE
- 회원이 좋아요 취소한 이벤트 테이블의 좋아요수 감소

### 3. 참고 사항

- 이벤트좋아요관리 테이블에 **먼저 INSERT 후**, 이벤트의 좋아요수 증가하기
- 이벤트좋아요관리 테이블에서 **먼저 DELETE 후**, 이벤트의 좋아요수 감소하기

**Comment by goeunpark123** [comment]
트리거를 사용하여 자동 업데이트 대단해요!

**Comment by mini-xi** [comment]
트리거가 되게 유용한 것 같습니다 활용 부분이 많네요

**Comment by Wrinkk** [comment]
트리거 활용 멋집니다! 👍

**Comment by onelee521** [comment]
트리거가 유용하네요
