### ISSUE TITLE
이벤트 댓글 작성 기능 추가

### ISSUE THREAD

**Issue by Wrinkk** [beyond-sw-camp/be04-1st-4goda-vite#51]
### 1. 목적

- 기존의 약속이 취소 되는경우 이벤트를 취소하기 위함.

### 2. 기능 설명

- 이벤트 댓글 작성 기능 추가

- 이벤트 후 이벤트에 대한 후기를 남기기 위한 기능

**Comment by Sosohy** [comment]
목적이 잘못 써져있는 것  같아요! 그 외에 댓글기능은 좋습니다!

**Comment by onelee521** [comment]
목적 변경이 필요한 것 같습니다.

**Comment by ms1011** [comment]
기능은 훌륭하나 목적 변경하여 주시면 될 것 같습니다 @Wrinkk 😸
