### ISSUE TITLE
이벤트 댓글 수정 기능 추가

### ISSUE THREAD

**Issue by Wrinkk** [beyond-sw-camp/be04-1st-4goda-vite#52]
### 1. 목적

- 이벤트 댓글 내용의 수정이 필요할 시 의 상황을 위한 목적

### 2. 기능 설명

- 이벤트 댓글 내용을 수정하는 기능

**Comment by mini-xi** [comment]
이벤트 댓글 수정 기능은 꼭 필요하죠!

**Comment by ms1011** [comment]
좋은 기능인 것 같아요 👍👍
