### ISSUE TITLE
이벤트 댓글 삭제 기능 추가

### ISSUE THREAD

**Issue by Wrinkk** [beyond-sw-camp/be04-1st-4goda-vite#53]
### 1. 목적

- 이벤트 후 이벤트 댓글 작성 한후 삭제를 할 이유가 생겼을 시를 위함.

### 2. 기능 설명

- 이벤트에 작성했던 댓글을 삭제하는 기능

**Comment by mini-xi** [comment]
댓글 삭제 만약 계정이 정지됐으면 자동으로 삭제되나요?

**Comment by onelee521** [comment]
DB에서도 정보가 사라지나요?

**Comment by ms1011** [comment]
DB에서는 사라지지 않고 표면적으로 보이지 않게 처리하면 좋은 것 같습니다 😸
