### ISSUE TITLE
이벤트 좋아요를 추천순으로 정렬

### ISSUE THREAD

**Issue by mini-xi** [beyond-sw-camp/be04-1st-4goda-vite#54]
### 1. 목적

> 이벤트를 좋아요 추천순으로 정렬하고 많이 받은 추천순으로(내림차순) 정렬

### 2. 기능 설명

- 이벤트 좋아요를 추천순으로 정렬하고 내림차순으로 확인

**Comment by goeunpark123** [comment]
오름차순이 아닌 내림차순 정렬이 의미 있는 것 같습니다

**Comment by Sosohy** [comment]
다른 회원들이 퀄리티 높은 이벤트를 참고하기에 좋을 것 같아요.

**Comment by onelee521** [comment]
추천순으로 정렬하면 어떤 템플릿이 인기 많은지도 알 수 있을 것 같습니다.
