### ISSUE TITLE
회원별 작성 이벤트 댓글 조회 기능 추가

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-1st-4goda-vite#55]
### 1. 목적

> 회원별 작성 이벤트댓글 조회
> 

### 2. 기능 설명

- 특정 회원이 작성한 이벤트댓글 내용 확인
- 특정 회원이 작성한 이벤트댓글 작성시간 확인

### 3. 참고 사항

조회가 자주 되는 항목이므로 VIEW 사용

**Comment by mini-xi** [comment]
이벤트 댓글 조회할 때 어떤 식으로 나타날지 프론트 관련 부분도 생각해볼까요?

**Comment by Sosohy** [comment]
네 좋아요~

**Comment by onelee521** [comment]
확인했습니다~
