### ISSUE TITLE
이벤트 주최 회원 닉네임 확인 기능 추가

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-1st-4goda-vite#56]
### 1. 목적

> 이벤트 주최 회원 닉네임 조회
> 

### 2. 기능 설명

- 이벤트를 주최한 회원의 닉네임 확인
- 주최한 이벤트의 제목 확인

### 3. 참고 사항

조회가 자주 되는 항목이므로 VIEW 사용

**Comment by Sosohy** [comment]
넵 뷰로 만드는게 좋을 것  같아요.

**Comment by onelee521** [comment]
조회가 자주 되는 항목이라 뷰로 만드는 거 좋습니다.

**Comment by ms1011** [comment]
뷰로 만들면 조회 속도가 좋아질 것으로 보이네요 좋아요 ☺️☺️
