### ISSUE TITLE
이벤트 카테고리별 이벤트 목록 확인 기능 추가

### ISSUE THREAD

**Issue by Wrinkk** [beyond-sw-camp/be04-1st-4goda-vite#57]
### 1. 목적

- 이벤트의 카테고리 별로 이벤트를 정리해서 보기 위한 편의성 제공

### 2. 기능 설명

- 이벤트를 카테고리 별로 정리하여 보는 기능

**Comment by goeunpark123** [comment]
카테고리 별로 이벤트를 확인해서 참고하기 좋을 것 같습니다

**Comment by Sosohy** [comment]
네 좋아요~

**Comment by ms1011** [comment]
더욱 편해지겠네요 좋습니다 ☺️☺️
