### ISSUE TITLE
결제 기능 추가

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-1st-4goda-vite#58]
### 1. 목적

> 결제
> 

### 2. 기능 설명

- 결제가 완료되는 순간 결제 테이블에 결제 정보 INSERT

### 3. 참고 사항

**Comment by mini-xi** [comment]
결제기능 추가 좋습니다.. 필요한 기능이었어요

**Comment by Wrinkk** [comment]
결제 자체는 외부에서 진행되나요?

**Comment by onelee521** [comment]
확인했습니다
