### ISSUE TITLE
환불 신청

### ISSUE THREAD

**Issue by mini-xi** [beyond-sw-camp/be04-1st-4goda-vite#60]
### 1. 목적

> 환불 기능 확인을 위한 데이터 삽입

### 2. 기능 설명

- 환불 데이터를 삽입하고 환불 테스트

**Comment by goeunpark123** [comment]
환불 상태 속성에 대해 더 설명해주시면 좋을 것 같아요

**Comment by onelee521** [comment]
확인했습니다

**Comment by ms1011** [comment]
필수 기능이네요 좋아요 👍👍
