### ISSUE TITLE
환불 완료

### ISSUE THREAD

**Issue by mini-xi** [beyond-sw-camp/be04-1st-4goda-vite#61]
### 1. 목적

> 환불 기능 확인을 위한 데이터 삽입

### 2. 기능 설명

- 환불 데이터를 삽입하고 환불 테스트

**Comment by goeunpark123** [comment]
환불 신청이 내용이 똑같네요?

**Comment by ms1011** [comment]
#60  환불 신청과 관련된 기능으로 아주 좋습니다 😸😸
