### ISSUE TITLE
초대장템플릿별 환불 내역 확인

### ISSUE THREAD

**Issue by mini-xi** [beyond-sw-camp/be04-1st-4goda-vite#63]
### 1. 목적

> 초대장 템플릿별로 환불 내역을 확인하고 사용가능여부 및 회원확인

### 2. 기능 설명

- 유료초대장 템플릿이 환불되었을 때 사용여부가 불가능으로 바뀌고 환불한 회원 확인 가능

**Comment by goeunpark123** [comment]
어떤 과정으로 실행되는지 궁금합니다! @mini-xi

**Comment by ms1011** [comment]
좋은 기능으로 보입니다! 😀

**Comment by Wrinkk** [comment]
중요한 기능 같습니다 👍
