### ISSUE TITLE
선물별 환불 내역 확인

### ISSUE THREAD

**Issue by mini-xi** [beyond-sw-camp/be04-1st-4goda-vite#64]
### 1. 목적

> 선물별로 환불 내역을 확인하고 회원 확인

### 2. 기능 설명

- 선물이 환불되었을 때 환불한 회원 및 환불상태 확인 가능

**Comment by goeunpark123** [comment]
갖고 싶은 선물이 환불되어서 호스트가 슬플 것 같습니다

**Comment by ms1011** [comment]
돈 관리를  위한 필수 기능 같습니다 좋아요 👍👍

**Comment by Wrinkk** [comment]
갑자기 불필요한 선물이 생겼을 때 필요한 거같아요!!
