### ISSUE TITLE
초대장템플릿 환불 과 등급 변경 기능 추가

### ISSUE THREAD

**Issue by Wrinkk** [beyond-sw-camp/be04-1st-4goda-vite#65]
### 1. 목적

- 기존에 결제한 내역을 환불 한 뒤에, 누적금액 변동 후 금액 기준에 따른 등급 변동을 체크하기 위함.

### 2. 기능 설명

- 초대장템플릿 환불 과 등급 변경 기능

**Comment by mini-xi** [comment]
이거 조금 어렵던데 다 같이 수정도 열심히 해봅시다

**Comment by onelee521** [comment]
트랜젝션을 사용하나요?

**Comment by ms1011** [comment]
환불의 경우 API를 사용하여 값이 들어오기 때문에 트리거를 사용하여 개발하였습니다 😌
