### ISSUE TITLE
초대장템플릿 데이터 삽입

### ISSUE THREAD

**Issue by mini-xi** [beyond-sw-camp/be04-1st-4goda-vite#66]
### 1. 목적

>  초대장 템플릿 관련 기능 확인을 위한 데이터 삽입

### 2. 기능 설명

- 초대장템플릿 데이터를 삽입하고 초대장템플릿 관련 기능 테스트

**Comment by goeunpark123** [comment]
좋은 기능입니다

**Comment by ms1011** [comment]
필수 기능입니다 좋아요 👍👍

**Comment by goeunpark123** [comment]
#96 확인 부탁드립니다!
