### ISSUE TITLE
초대장템플릿 수정

### ISSUE THREAD

**Issue by mini-xi** [beyond-sw-camp/be04-1st-4goda-vite#67]
### 1. 목적

> 초대장 템플릿 관련 기능 확인을 위한 데이터 업데이트

### 2. 기능 설명

- 초대장템플릿 데이터를 업데이트하고 초대장템플릿 관련 기능 테스트

**Comment by Sosohy** [comment]
네 확인했습니다~

**Comment by ms1011** [comment]
#66 [초대장템플릿 데이터 삽입]을 진행했으면 수정도 가능한 것이 아주 좋아보입니다. 😌👍👍
