### ISSUE TITLE
초대장템플릿 삭제

### ISSUE THREAD

**Issue by mini-xi** [beyond-sw-camp/be04-1st-4goda-vite#68]
### 1. 목적

> 초대장 템플릿 관련 기능 확인을 위한 데이터 삭제

### 2. 기능 설명

- 초대장템플릿 데이터를 삭제하고 초대장템플릿 관련 기능 테스트

**Comment by Sosohy** [comment]
초대장 템플릿을 아예 삭제하기 보다는 삭제 일자를 넣어도 좋을 것 같습니다.

**Comment by Sosohy** [comment]
또 해당 템플릿을 삭제했을 때, 템플릿을 구매한 회원은 어떻게 이용하게 되는지에 대해서도 생각해보는 게 좋을 것 같아요

**Comment by ms1011** [comment]
#66 #67 [초대장템플릿 입력,수정]과 함께 삭제 기능 아주 좋습니다👍👍👍
