### ISSUE TITLE
초대장템플릿 목록 확인 기능

### ISSUE THREAD

**Issue by Sosohy** [beyond-sw-camp/be04-1st-4goda-vite#69]
### 1. 목적

> 전체 초대장템플릿을 확인하기 위한 템플릿 목록 조회
> 

### 2. 기능 설명

- 초대장템플릿 테이블의 초대장템플릿정보 SELECT

**Comment by mini-xi** [comment]
초대장템플릿 목록 확인이 유저가 할 수 있는거 맞죠? 어떤 템플릿이 있는지

**Comment by ms1011** [comment]
초대장템플릿 목록 확인은 비회원도 가능하게 하는게 좋을 것 같습니다 👍👍

**Comment by Wrinkk** [comment]
확인 했습니다!
