### ISSUE TITLE
초대장템플릿 좋아요 기능 추가

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-1st-4goda-vite#70]
### 1. 목적

> 초대장템플릿 좋아요를 누르는 순간 초대장템플릿의 좋아요수에 반영
> 

### 2. 기능 설명

- 초대장템플릿좋아요관리 테이블에 좋아요 정보 INSERT
- 초대장템플릿 테이블에 좋아요수 UPDATE

### 3. 참고 사항

트리거를 생성하여 INSERT가 발생하면 자동 UPDATE

**Comment by Sosohy** [comment]
넵 확인했습니다. 해당 이슈도 제대로 적용되는지 확인을 해봐야 할 것 같아요!

**Comment by ms1011** [comment]
템플릿 좋아요를 통해 어떤 템플릿이 인기가 좋은 지 알 수 있을 것 같네요 ㅎㅎ 😀😀

**Comment by Wrinkk** [comment]
인기순으로 초대장 확인하는건 중요하죠!!
