### ISSUE TITLE
초대장템플릿 좋아요 취소 기능 추가

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-1st-4goda-vite#71]
### 1. 목적

> 초대장템플릿 좋아요를 취소하는 순간 초대장템플릿의 좋아요수에 반영
> 

### 2. 기능 설명

- 초대장템플릿좋아요관리 테이블에 좋아요 내역 DELETE
- 초대장템플릿 테이블에 좋아요수 UPDATE

### 3. 참고 사항

트리거를 생성하여 DELETE가 발생하면 자동 UPDATE

**Comment by Sosohy** [comment]
좋아요수 제대로 반영되는지 확인이 중요할 것 같습니다!

**Comment by ms1011** [comment]
#70 [템플릿 좋아요 기능 추가]와 함께 취소 기능도 있어 아주 좋습니다 👍👍

**Comment by Wrinkk** [comment]
템플릿 좋아요 기능 이랑 확인했습니다~
