### ISSUE TITLE
초대장템플릿 좋아요 추천순 검색 기능 추가

### ISSUE THREAD

**Issue by ms1011** [beyond-sw-camp/be04-1st-4goda-vite#74]
### 1. 목적

> 초대장템플릿을 좋아요 순으로 검색하여 인기가 많은 템플릿을 먼저 검색하기 위함

### 2. 기능 설명

- 초대장템플릿 테이블에서 SELECT한 초대장템플릿정보를 좋아요수로 내림차순 정렬

**Comment by mini-xi** [comment]
좋아요 순으로 봤을 때 회원한테 좋은거죠? 기능에 대해서 생각해봐야겠네요

**Comment by ms1011** [comment]
> 좋아요 순으로 봤을 때 회원한테 좋은거죠? 기능에 대해서 생각해봐야겠네요

어느게 인기있는 지 확인 할 수 있어 좋은 것 같습니다 ☺️

**Comment by Wrinkk** [comment]
인기순으로 확인할수 있는게 좋은거같습니다!
