### ISSUE TITLE
초대장템플릿 결제 기능 추가

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-1st-4goda-vite#76]
### 1. 목적

> 초대장템플릿 결제
> 

### 2. 기능 설명

- 결제 테이블에 결제 정보 INSERT
- 초대장템플릿결제 테이블에 결제 정보 INSERT
- 회원 테이블의 누적결제금액 UPDATE
- 변경된 누적결제금액에 따라 회원등급 UPDATE

### 3. 참고 사항

트랜젝션으로 네 개의 쿼리가 한 번에 실행

**Comment by mini-xi** [comment]
유료 초대장 관련해서 연결되는 테이블을 잘 알아야할 것 같습니다

**Comment by Sosohy** [comment]
순서도 중요할 것 같아요!

**Comment by Wrinkk** [comment]
잘 작동하는지 체크를 잘해야겠습니다.
