### ISSUE TITLE
카테고리 별 사용된 초대장 템플릿 확인 기능 추가

### ISSUE THREAD

**Issue by Wrinkk** [beyond-sw-camp/be04-1st-4goda-vite#77]
### 1. 목적

- 카테고리 별 사용된 초대장 템플릿을 확인하기 위해 JOIN을 사용하였고, 여러번 사용 했기에, VIEW를 통한 빠른 조회를 하기위함.

### 2. 기능 설명

- 카테고리 별 사용된 초대장 템플릿을 확인

**Comment by mini-xi** [comment]
카테고리 항목도 확인을 해야될 것 같습니다. 수고하셨습니다!

**Comment by onelee521** [comment]
목적과 기능설명이 바뀌어야하지 않나 싶어요
