### ISSUE TITLE
가격별 초대장템플릿 확인 기능 추가

### ISSUE THREAD

**Issue by Wrinkk** [beyond-sw-camp/be04-1st-4goda-vite#78]
### 1. 목적

- 주기별로 초대장이 바뀔 거라 생각을 하기에, 변경이 적고 데이터 양이 많은 테이블의 빠른 조회를 위해 INDEX를 사용하여 빠른 조회.

### 2. 기능 설명

- 가격 별 초대장템플릿 확인

**Comment by mini-xi** [comment]
유료 초대장이 몇 개 있는지 확인 해본 후에 저도 테스트 해볼게요

**Comment by onelee521** [comment]
인덱스 사용 좋습니다.
