### ISSUE TITLE
선물 등록 기능 추가

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-1st-4goda-vite#79]
### 1. 목적

> 이벤트 호스트가 받고 싶은 선물을 등록
> 

### 2. 기능 설명

- 선물 테이블에 받고 싶은 선물 정보 INSERT

### 3. 참고 사항

**Comment by Sosohy** [comment]
호스트가 여러개의 선물 등록도 가능한가요?

**Comment by onelee521** [comment]
선물을 여러개 등록하고 싶으면 어떻게 하나요?

**Comment by ms1011** [comment]
재미있는 기능입니다 😀😀
