### ISSUE TITLE
선물 결제 기능 추가

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-1st-4goda-vite#80]
### 1. 목적

> 이벤트 게스트가 선물을 결제 완료하는 순간 선물의 모인금액에 반영
> 

### 2. 기능 설명

- 선물결제 테이블에 결제 정보 INSERT
- 선물 테이블의 모인금액 UPDATE

### 3. 참고 사항

트리거를 생성하여 INSERT가 발생하면 자동 UPDATE

**Comment by Sosohy** [comment]
넵 확인했습니다~

**Comment by onelee521** [comment]
확인했습니다.

**Comment by ms1011** [comment]
좋은 기능입니다 ☺️
