### ISSUE TITLE
선물 결제 취소 기능 추가

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-1st-4goda-vite#81]
### 1. 목적

> 이벤트 게스트가 선물을 환불 완료하는 순간 선물의 모인금액에 반영
> 

### 2. 기능 설명

- 선물결제 테이블에 환불 상태 UPDATE
- 선물 테이블의 모인금액 UPDATE

### 3. 참고 사항

트리거를 생성하여 UPDATE가 발생하면 자동 UPDATE

**Comment by Sosohy** [comment]
하나하나 직접 인서트보다 한번에 트리거로 실행되는거 좋은 기능 같아요~

**Comment by onelee521** [comment]
업데이트가 한 번에 이루어져서 유용합니다.

**Comment by ms1011** [comment]
#80 [선물 결제 기능]과 함께 진행 되면 좋을 것 같습니다 😀😀
