### ISSUE TITLE
선물 모인금액 확인 기능 추가

### ISSUE THREAD

**Issue by ms1011** [beyond-sw-camp/be04-1st-4goda-vite#82]
### 1. 목적

> 선물 펀딩 가격이 얼마나 모였는 지 확인을 위함

### 2. 기능 설명

- 선물 하나에 대한 선물 테이블의 모인 금액 조회

**Comment by Sosohy** [comment]
펀딩 금액 확인할 때 얼마를 더 모아야 하는지 확인하기 좋을 것 같아요!
