### ISSUE TITLE
게스트명단확인 기능

### ISSUE THREAD

**Issue by Sosohy** [beyond-sw-camp/be04-1st-4goda-vite#83]
### 1. 목적

> 한 이벤트에 초대된 게스트들의 정보를 얻고 이벤트 참석자를 관리하기 위해 게스트의 정보목록 조회
> 

### 2. 기능 설명

- 한 이벤트에 대한 게스트들의  명단정보 조회

### 3. 참고 사항

- 게스트의 이메일과 전화번호, 참석여부를 확인
- 발송이 제대로 완료되었는지 확인하기 위한 is_send 정보도 함께 받아오기

**Comment by goeunpark123** [comment]
발송여부를 확인할 수 있어 좋은 기능인 것 같습니다

**Comment by ms1011** [comment]
꼭 필수적인 기능인 것 같네요 👍👍

**Comment by Wrinkk** [comment]
확인 했습니다!
