### ISSUE TITLE
이벤트 참석자 명단 확인 기능 추가

### ISSUE THREAD

**Issue by Wrinkk** [beyond-sw-camp/be04-1st-4goda-vite#84]
### 1. 목적

- 게스트 명단에서 이벤트 참석 여부를 체크하기 위함.

### 2. 기능 설명

- 이벤트 참석자 명단 확인 기능

### 3. 참고 사항

**Comment by goeunpark123** [comment]
테이블 JOIN을 하나요?

**Comment by Sosohy** [comment]
비회원인 게스트도 참석 여부를 확인할 수 있는건가요?

**Comment by ms1011** [comment]
게스트명단뿐 아니라 참석 여부를 볼 수 있어 좋습니다 😀😀
