### ISSUE TITLE
공지사항 작성 기능 추가

### ISSUE THREAD

**Issue by ms1011** [beyond-sw-camp/be04-1st-4goda-vite#88]
### 1. 목적

> 운영진들이 회원들에게 공지사항을 알리기 위해

### 2. 기능 설명

- 공지사항 글 작성 기능

**Comment by mini-xi** [comment]
공지사항 작성된 양식 알려주시면 감사하겠습니다

**Comment by Sosohy** [comment]
게시글 자체 형식으로 공지사항도 작성가능한가요?

**Comment by ms1011** [comment]
> 게시글 자체 형식으로 공지사항도 작성가능한가요?

네 가능합니다. 일반 글 작성과 같은 형식으로 진행 됩니다 😀

**Comment by ms1011** [comment]
> 공지사항 작성된 양식 알려주시면 감사하겠습니다
- 제목
[공지사항] 바이트 서버 점검 안내
- 내용
안녕하세요. 바이트 담당자입니다. 일정이 변경되어 이번주 금요일 서버 점검이 시작될 예정입니다.
추가적으로 시간, 작성자 표현이 될 것 같습니다

**Comment by Wrinkk** [comment]
확인했습니다.
