### ISSUE TITLE
문의사항별 답변확인

### ISSUE THREAD

**Issue by Sosohy** [beyond-sw-camp/be04-1st-4goda-vite#91]
### 1. 목적

> 문의사항에 따른 답변을 확인하기 위해 문의사항의 정보와 해당 문의사항에 따른 답변 조회
> 

### 2. 기능 설명

- 문의사항제목과 문의카테고리종류, 해당 문의사항에 대한 답변 조회

### 3. 참고 사항

- 문의카테고리, 문의사항, 답변 테이블 JOIN 필요

**Comment by goeunpark123** [comment]
문의사항과 답변을 한 눈에 볼 수 있어 좋습니다.

**Comment by onelee521** [comment]
문의사항에 따른 답변 보기 좋은 것 같습니다.

**Comment by ms1011** [comment]
문의사항별로 볼 수 있는게 좋습니다 😸😸
