### ISSUE TITLE
회원별 작성 게시글 확인 기능 추가

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-1st-4goda-vite#93]
### 1. 목적

> 회원별 작성 게시글 조회
> 

### 2. 기능 설명

- 특정 회원이 작성한 게시글 확인

### 3. 참고 사항

조회가 자주 되는 항목이므로 VIEW 사용

**Comment by mini-xi** [comment]
특정 회원 게시글이면 JOIN문으로 하시면 될 것 같습니다

**Comment by Sosohy** [comment]
네 좋은 것 같아요~

**Comment by ms1011** [comment]
좋은 기능같습니다 👍👍
