### ISSUE TITLE
회원등급별 할인 적용

### ISSUE THREAD

**Issue by Sosohy** [beyond-sw-camp/be04-1st-4goda-vite#94]
### 1. 목적

> 회원의 회원 등급에 따른 할인율을 적용한 가격을 표시하기 위해 초대장템플릿 최종결제금액 조회
> 

### 2. 기능 설명

- 한 회원에 대해 회원등급별 할인율 적용한 초대장템플릿 결제 금액 조회

### 3. 참고 사항

- 등급 별로 할인율이 다르니 등급별 할인율을 적용해서 계산하기!

**Comment by mini-xi** [comment]
제가 수정해보겠습니다

**Comment by onelee521** [comment]
등급별 할인적용 바뀌지 않게 잘 봐야겠어요

**Comment by ms1011** [comment]
할인율이 적용되어 더욱 좋은 가격으로 구매할 수 있을 것 같네요 ☺️☺️
