### ISSUE TITLE
선물별 결제 회원 확인

### ISSUE THREAD

**Issue by onelee521** [beyond-sw-camp/be04-1st-4goda-vite#95]
### 1. 목적

> 선물별 결제 회원 목록을 확인하기
> 

### 2. 기능 설명

- 선물 하나 당 누가 선물 결제에 참여했는지 확인한다.

**Comment by mini-xi** [comment]
JOIN문 사용해서 하면 될 것 같네요

**Comment by Sosohy** [comment]
선물결제금액까지 표시해도 좋을 것 같아요!

**Comment by ms1011** [comment]
누가 결제했는지 확인하는 기능 아주 좋네요 😸
